CREATE TABLE users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name   VARCHAR(80)  NOT NULL,
    last_name    VARCHAR(80)  NOT NULL,
    email        VARCHAR(150) NOT NULL,
    phone_number VARCHAR(20)  NOT NULL,
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP
);

CREATE UNIQUE INDEX ux_users_email ON users (email);
CREATE UNIQUE INDEX ux_users_phone_number ON users (phone_number);

CREATE TABLE accounts (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institution_code VARCHAR(6)  NOT NULL,
    account_number   VARCHAR(10) NOT NULL,
    user_id          BIGINT,
    account_type     VARCHAR(20) NOT NULL,
    currency         VARCHAR(3)  NOT NULL,
    status           VARCHAR(20) NOT NULL,
    created_at       TIMESTAMP   NOT NULL,
    updated_at       TIMESTAMP,
    CONSTRAINT fk_accounts_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE UNIQUE INDEX ux_accounts_institution_number ON accounts (institution_code, account_number);
CREATE INDEX ix_accounts_user_id ON accounts (user_id);

CREATE TABLE wallet_balances (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT        NOT NULL,
    balance    NUMERIC(19,4) NOT NULL DEFAULT 0,
    version    BIGINT        NOT NULL DEFAULT 0,
    updated_at TIMESTAMP,
    CONSTRAINT fk_wallet_balances_account FOREIGN KEY (account_id) REFERENCES accounts (id)
);

CREATE UNIQUE INDEX ux_wallet_balances_account_id ON wallet_balances (account_id);

CREATE SEQUENCE nuban_serial_seq START WITH 100000001 INCREMENT BY 1;
