CREATE TABLE wallet_transactions (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference              VARCHAR(40)   NOT NULL,
    idempotency_key        VARCHAR(120),
    request_hash           VARCHAR(64),
    transaction_type       VARCHAR(20)   NOT NULL,
    status                 VARCHAR(20)   NOT NULL,
    source_account_id      BIGINT        NOT NULL,
    destination_account_id BIGINT        NOT NULL,
    amount                 NUMERIC(19,4) NOT NULL,
    currency               VARCHAR(3)    NOT NULL,
    narration              VARCHAR(255),
    failure_reason         VARCHAR(64),
    created_at             TIMESTAMP     NOT NULL,
    completed_at           TIMESTAMP,
    CONSTRAINT fk_tx_source_account FOREIGN KEY (source_account_id) REFERENCES accounts (id),
    CONSTRAINT fk_tx_destination_account FOREIGN KEY (destination_account_id) REFERENCES accounts (id),
    CONSTRAINT ck_tx_amount_positive CHECK (amount > 0)
);

CREATE UNIQUE INDEX ux_wallet_transactions_reference ON wallet_transactions (reference);
CREATE UNIQUE INDEX ux_wallet_transactions_idempotency_key ON wallet_transactions (idempotency_key);
CREATE INDEX ix_wallet_transactions_source ON wallet_transactions (source_account_id);
CREATE INDEX ix_wallet_transactions_destination ON wallet_transactions (destination_account_id);

CREATE TABLE ledger_entries (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT        NOT NULL,
    account_id     BIGINT        NOT NULL,
    direction      VARCHAR(10)   NOT NULL,
    amount         NUMERIC(19,4) NOT NULL,
    balance_before NUMERIC(19,4) NOT NULL,
    balance_after  NUMERIC(19,4) NOT NULL,
    narration      VARCHAR(255),
    created_at     TIMESTAMP     NOT NULL,
    CONSTRAINT fk_ledger_transaction FOREIGN KEY (transaction_id) REFERENCES wallet_transactions (id),
    CONSTRAINT fk_ledger_account FOREIGN KEY (account_id) REFERENCES accounts (id),
    CONSTRAINT ck_ledger_amount_positive CHECK (amount > 0)
);

CREATE INDEX ix_ledger_entries_account_created ON ledger_entries (account_id, created_at);
CREATE INDEX ix_ledger_entries_transaction ON ledger_entries (transaction_id);
